apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldapext-service
  namespace: integration
spec:
  ports:
  - nodePort: 30001
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    app: ldap
  sessionAffinity: None
  type: NodePort
